query PreviewLiquidQuery($liquid: String!) {
  previewLiquid(content: $liquid)
}

query PreviewMarkdownQuery($markdown: String!) {
  previewMarkdown(markdown: $markdown)
}

query PreviewNotifierLiquidQuery($eventKey: String!, $liquid: String!) {
  previewLiquid: previewNotifierLiquid(eventKey: $eventKey, content: $liquid)
}
