query EventListQuery($page: Int, $filters: EventFiltersInput, $sort: [SortInput]) {
  convention {
    id
    name
    starts_at
    ends_at
    timezone_name

    events_paginated(page: $page, per_page: 20, filters: $filters, sort: $sort) {
      total_entries
      total_pages
      current_page
      per_page

      entries {
        id
        category
        title
        created_at
        short_blurb_html
        form_response_attrs_json

        runs {
          id
          starts_at
        }
      }
    }
  }

  myProfile {
    id
    ability {
      can_read_schedule
    }
  }
}
