#import './queries.gql'

mutation CreateLayout($cmsLayout: CmsLayoutInput!) {
  createCmsLayout(input: { cms_layout: $cmsLayout }) {
    cms_layout {
      ...CmsLayoutFields
    }
  }
}

mutation UpdateLayout($id: Int!, $cmsLayout: CmsLayoutInput!) {
  updateCmsLayout(input: { id: $id, cms_layout: $cmsLayout }) {
    cms_layout {
      ...CmsLayoutFields
    }
  }
}

mutation DeleteLayout($id: Int!) {
  deleteCmsLayout(input: { id: $id }) {
    clientMutationId
  }
}
