#import "./queries.gql"

mutation CreateEventCategory($eventCategory: EventCategoryInput!) {
  createEventCategory(input: { event_category: $eventCategory }) {
    event_category {
      id
      ...EventCategoryFields
    }
  }
}

mutation UpdateEventCategory($id: Int!, $eventCategory: EventCategoryInput!) {
  updateEventCategory(input: { id: $id, event_category: $eventCategory }) {
    event_category {
      id
      ...EventCategoryFields
    }
  }
}

mutation DeleteEventCategory($id: Int!) {
  deleteEventCategory(input: { id: $id }) {
    clientMutationId
  }
}
