fragment EventCategoryFields on EventCategory {
  id
  name
  team_member_name
  proposal_description
  scheduling_ui
  default_color
  signed_up_color
  full_color
  can_provide_tickets

  events_paginated {
    total_entries
  }

  department {
    id
    name
  }

  event_form {
    id
    title
  }

  event_proposal_form {
    id
    title
  }
}

query EventCategoryAdminQuery {
  convention {
    id
    name
    ticket_name
    ticket_mode

    departments {
      id
      name
    }

    event_categories {
      id
      ...EventCategoryFields
    }

    forms {
      id
      title
      form_type
    }
  }
}
