/* eslint-disable */
/** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
import * as Types from '../graphqlTypes.generated';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
/** Autogenerated input type of CreateOAuthApplication */
export type CreateOAuthApplicationInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: string | null | undefined;
  /** Attributes for the new OAuth2 application. */
  oauth_application: OAuthApplicationInput;
};

/** Autogenerated input type of DeleteOAuthApplication */
export type DeleteOAuthApplicationInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: string | null | undefined;
  /** The ID of the OAuth2 application to delete. */
  id: string | number;
};

/** Input for creating or updating an OAuth2 application. */
export type OAuthApplicationInput = {
  /** Whether the application can keep its client secret confidential. */
  confidential?: boolean | null | undefined;
  /** The display name of the application. */
  name?: string | null | undefined;
  /** The allowed redirect URI(s), one per line. */
  redirect_uri?: string | null | undefined;
  /** The OAuth scopes this application is allowed to request. */
  scopes?: Array<string> | null | undefined;
};

/** Autogenerated input type of RegenerateOAuthApplicationSecret */
export type RegenerateOAuthApplicationSecretInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: string | null | undefined;
  /** The ID of the OAuth2 application. */
  id: string | number;
};

/** Autogenerated input type of UpdateOAuthApplication */
export type UpdateOAuthApplicationInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: string | null | undefined;
  /** The ID of the OAuth2 application to update. */
  id: string | number;
  /** Updated attributes for the OAuth2 application. */
  oauth_application: OAuthApplicationInput;
};

export type CreateOAuthApplicationMutationVariables = Exact<{
  input: Types.CreateOAuthApplicationInput;
}>;


export type CreateOAuthApplicationMutationData = { __typename: 'Mutation', createOAuthApplication: { __typename: 'CreateOAuthApplicationPayload', secret: string, oauth_application: { __typename: 'OAuthApplication', id: string, name: string, uid: string, redirect_uri: string | null, scopes: Array<string>, confidential: boolean, is_intercode_frontend: boolean } } };

export type UpdateOAuthApplicationMutationVariables = Exact<{
  input: Types.UpdateOAuthApplicationInput;
}>;


export type UpdateOAuthApplicationMutationData = { __typename: 'Mutation', updateOAuthApplication: { __typename: 'UpdateOAuthApplicationPayload', oauth_application: { __typename: 'OAuthApplication', id: string, name: string, uid: string, redirect_uri: string | null, scopes: Array<string>, confidential: boolean, is_intercode_frontend: boolean } } };

export type DeleteOAuthApplicationMutationVariables = Exact<{
  input: Types.DeleteOAuthApplicationInput;
}>;


export type DeleteOAuthApplicationMutationData = { __typename: 'Mutation', deleteOAuthApplication: { __typename: 'DeleteOAuthApplicationPayload', oauth_application: { __typename: 'OAuthApplication', id: string } } };

export type RegenerateOAuthApplicationSecretMutationVariables = Exact<{
  input: Types.RegenerateOAuthApplicationSecretInput;
}>;


export type RegenerateOAuthApplicationSecretMutationData = { __typename: 'Mutation', regenerateOAuthApplicationSecret: { __typename: 'RegenerateOAuthApplicationSecretPayload', secret: string, oauth_application: { __typename: 'OAuthApplication', id: string, name: string, uid: string, redirect_uri: string | null, scopes: Array<string>, confidential: boolean, is_intercode_frontend: boolean } } };


export const CreateOAuthApplicationDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"CreateOAuthApplication"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"input"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"CreateOAuthApplicationInput"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"createOAuthApplication"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"Variable","name":{"kind":"Name","value":"input"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"oauth_application"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"FragmentSpread","name":{"kind":"Name","value":"OAuthApplicationFields"}}]}},{"kind":"Field","name":{"kind":"Name","value":"secret"}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"OAuthApplicationFields"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"OAuthApplication"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"uid"}},{"kind":"Field","name":{"kind":"Name","value":"redirect_uri"}},{"kind":"Field","name":{"kind":"Name","value":"scopes"}},{"kind":"Field","name":{"kind":"Name","value":"confidential"}},{"kind":"Field","name":{"kind":"Name","value":"is_intercode_frontend"}}]}}]} as unknown as DocumentNode<CreateOAuthApplicationMutationData, CreateOAuthApplicationMutationVariables>;
export const UpdateOAuthApplicationDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"UpdateOAuthApplication"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"input"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"UpdateOAuthApplicationInput"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"updateOAuthApplication"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"Variable","name":{"kind":"Name","value":"input"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"oauth_application"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"FragmentSpread","name":{"kind":"Name","value":"OAuthApplicationFields"}}]}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"OAuthApplicationFields"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"OAuthApplication"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"uid"}},{"kind":"Field","name":{"kind":"Name","value":"redirect_uri"}},{"kind":"Field","name":{"kind":"Name","value":"scopes"}},{"kind":"Field","name":{"kind":"Name","value":"confidential"}},{"kind":"Field","name":{"kind":"Name","value":"is_intercode_frontend"}}]}}]} as unknown as DocumentNode<UpdateOAuthApplicationMutationData, UpdateOAuthApplicationMutationVariables>;
export const DeleteOAuthApplicationDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"DeleteOAuthApplication"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"input"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"DeleteOAuthApplicationInput"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"deleteOAuthApplication"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"Variable","name":{"kind":"Name","value":"input"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"oauth_application"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}}]}}]}}]}}]} as unknown as DocumentNode<DeleteOAuthApplicationMutationData, DeleteOAuthApplicationMutationVariables>;
export const RegenerateOAuthApplicationSecretDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"RegenerateOAuthApplicationSecret"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"input"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"RegenerateOAuthApplicationSecretInput"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"regenerateOAuthApplicationSecret"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"Variable","name":{"kind":"Name","value":"input"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"oauth_application"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"FragmentSpread","name":{"kind":"Name","value":"OAuthApplicationFields"}}]}},{"kind":"Field","name":{"kind":"Name","value":"secret"}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"OAuthApplicationFields"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"OAuthApplication"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"uid"}},{"kind":"Field","name":{"kind":"Name","value":"redirect_uri"}},{"kind":"Field","name":{"kind":"Name","value":"scopes"}},{"kind":"Field","name":{"kind":"Name","value":"confidential"}},{"kind":"Field","name":{"kind":"Name","value":"is_intercode_frontend"}}]}}]} as unknown as DocumentNode<RegenerateOAuthApplicationSecretMutationData, RegenerateOAuthApplicationSecretMutationVariables>;