#import "./queries.graphql"
#import "../queries.graphql"

mutation CreateMySignup($runId: ID!, $requestedBucketId: ID, $noRequestedBucket: Boolean) {
  createMySignup(
    input: { runId: $runId, requestedBucketId: $requestedBucketId, no_requested_bucket: $noRequestedBucket }
  ) {
    signup {
      id
      ...MySignupFields

      run {
        id
        ...EventPageRunFields
        ...RunBasicSignupData
      }
    }
  }
}

mutation WithdrawMySignup($runId: ID!) {
  withdrawMySignup(input: { runId: $runId }) {
    signup {
      id
      ...MySignupFields

      run {
        id
        ...EventPageRunFields
        ...RunBasicSignupData
      }
    }
  }
}

mutation CreateSignupRequest($targetRunId: ID!, $requestedBucketId: ID, $replaceSignupId: ID) {
  createSignupRequest(
    input: { targetRunId: $targetRunId, requestedBucketId: $requestedBucketId, replaceSignupId: $replaceSignupId }
  ) {
    signup_request {
      id
      ...MySignupRequestFields
    }
  }
}

mutation WithdrawSignupRequest($id: ID!) {
  withdrawSignupRequest(input: { id: $id }) {
    signup_request {
      id
      ...MySignupRequestFields
    }
  }
}

mutation CreateSignupRankedChoice($targetRunId: ID!, $requestedBucketId: ID) {
  createSignupRankedChoice(input: { targetRunId: $targetRunId, requestedBucketId: $requestedBucketId }) {
    signup_ranked_choice {
      id
      ...MySignupRankedChoiceFields
    }
  }
}
