version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: minitest-reporters
    versions:
    - "< 1.3.2, >= 1.3.1.a"
  - dependency-name: pg
    versions:
    - "< 1.1, >= 1.0.0.a"
  - dependency-name: phonelib
    versions:
    - 0.6.49
  - dependency-name: skylight
    versions:
    - 5.0.0
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: bootstrap.native
    versions:
    - "> 2.0.27"
  - dependency-name: file-loader
    versions:
    - "< 1.2, > 1.1.11"
  - dependency-name: mapbox-gl
    versions:
    - "> 1.13.0"
  - dependency-name: moment
    versions:
    - "> 2.25.2, < 3"
  - dependency-name: query-string
    versions:
    - "> 5.1.1"
  - dependency-name: sinon
    versions:
    - "< 1, >= 0.a"
  - dependency-name: "@types/mapbox-gl"
    versions:
    - "> 1.12.9"
  - dependency-name: "@types/react-select"
    versions:
    - 4.0.12
    - 4.0.13
    - 4.0.14
    - 4.0.4
  - dependency-name: js-yaml
    versions:
    - 4.0.0
  - dependency-name: caniuse-lite
    versions:
    - 1.0.30001181
  - dependency-name: sass
    versions:
    - 1.32.5
  - dependency-name: webpack
    versions:
    - 5.20.0
  - dependency-name: sass-loader
    versions:
    - 11.0.0
  - dependency-name: postcss
    versions:
    - 8.2.5
  - dependency-name: graphiql
    versions:
    - 1.4.0
  - dependency-name: react-dnd
    versions:
    - 13.1.1
    - 14.0.1
  - dependency-name: postcss-loader
    versions:
    - 5.0.0
    - 5.1.0
  - dependency-name: i18next
    versions:
    - 20.0.0
  - dependency-name: core-js
    versions:
    - 3.10.2
  - dependency-name: core-js-compat
    versions:
    - 3.10.0
  - dependency-name: "@apollo/client"
    versions:
    - 3.3.13
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
