---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    exclude_paths:
      # Mutations involve a bunch of boilerplate that's making duplication go nuts
      - app/graphql/mutations/
    config:
      languages:
        ruby:
        javascript:
          mass_threshold: 60
      javascript_plugins:
        - flow
  eslint:
    enabled: true
    config:
      config: .eslintrc.js
    checks:
      import/extensions:
        enabled: false
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.haml"
  - "**.rb"
  - "**.rhtml"
  - "**.slim"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
exclude_paths:
- config/
- db/
- script/
- test/
- vendor/
