inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-sequel

inherit_gem:
  prettier: rubocop.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - bin/bundle
    - bin/rails
    - bin/rake
    - bin/setup
    - bin/spring
    - bin/update
    - bin/webpack
    - bin/webpack-dev-server
    - bin/yarn
    - db/schema.rb
    - public/uploads/**/*.rb
    - script/rails

Sequel:
  Enabled: false
  Include: lib/intercode/import/**/*.rb

Style/BeginBlock:
  Description: 'Avoid the use of BEGIN blocks.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#no-BEGIN-blocks'
  Enabled: false

Style/ClassAndModuleChildren:
  Description: 'Checks style of children classes and modules.'
  Enabled: false

Style/CommentAnnotation:
  Description: 'Checks formatting of annotation comments.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#annotate-keywords'
  Enabled: false

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Style/DoubleNegation:
  Description: 'Checks for uses of double negation (!!).'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#no-bang-bang'
  Enabled: false

Metrics/AbcSize:
  Max: 30 # default is 17
  Exclude:
    - db/migrate/**/*.rb

Metrics/MethodLength:
  CountAsOne: ['array', 'heredoc']
  Max: 20 # default is 10
  Exclude:
    - db/migrate/**/*.rb
