language: ruby
sudo: false
rvm:
- 2.4.1
bundler_args: "--without development:production:intercode1_import"
cache:
  bundler: true
  directories:
    - node_modules
    - public/packs-test
  yarn: true
before_script:
- nvm install
- npm install --global yarn
- yarn install
- cp config/database.yml.ci config/database.yml
- bin/rake db:create db:migrate RAILS_ENV=test
notifications:
  slack:
    secure: Ca/xHuvVik0EfevEAmMuLH+Ybd2yj7FuYsSmxJ/4dyxisuKg+tUvnJEZxnrU/QtHOdSyIh3ZAA4gVHd8PALuJ0HYOjotogqCZaQ0ZYTB7pKVvxc8u8YK7aY3P58guib7SrU3iRXsvjaV5xOflaBY4Ng1TQrkc8TCU4i8xZhWxWc=
env:
- DATABASE=sqlite
- DATABASE=mysql
- DATABASE=postgresql
addons:
  code_climate:
    repo_token: 2ec5e525d523a261ed68d45eb18865e8ea7a5b32751290cabde2d44f39e78cce
after_success:
  - bundle exec codeclimate-test-reporter
