packageExtensions:
  "@docusaurus/lqip-loader@2.0.0-beta.13":
    dependencies:
      tslib: "*"
  "@docusaurus/responsive-loader@1.5.0":
    dependencies:
      sharp: "*"
  "@docusaurus/theme-classic@2.0.0-beta.13":
    dependencies:
      "@docusaurus/core": "^2.0.0-beta.13"
  autoprefixer@*:
    dependencies:
      colorette: "*"
  terser@*:
    dependencies:
      acorn: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.1.1.cjs

pnpEnableEsmLoader: true
