approvedGitRepositories:
  - "**"

enableScripts: true

packageExtensions:
  "@graphql-markdown/core@*":
    dependencies:
      "@graphql-markdown/diff": "*"
  "@graphql-markdown/logger@*":
    dependencies:
      "@docusaurus/logger": "*"
  autoprefixer@*:
    dependencies:
      colorette: "*"
  "framer-motion@*":
    dependencies:
      "@emotion/is-prop-valid": "*"

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-4.15.0.cjs
