packageExtensions:
  "@graphql-markdown/core@*":
    dependencies:
      "@graphql-markdown/diff": "*"
  "@graphql-markdown/logger@*":
    dependencies:
      "@docusaurus/logger": "*"
  "@n1ru4l/graphql-live-query@*":
    dependencies:
      tslib: "*"
  autoprefixer@*:
    dependencies:
      colorette: "*"

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-4.7.0.cjs
