plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-berry.cjs

packageExtensions:
  "@docusaurus/core@2.0.0-beta.6":
    dependencies:
      "@docusaurus/mdx-loader": "2.0.0-beta.6"
  "@docusaurus/mdx-loader@2.0.0-beta.6":
    dependencies:
      tslib: "*"
