packageExtensions:
  "@graphql-markdown/core@*":
    dependencies:
      "@graphql-markdown/diff": "*"
  "@graphql-markdown/logger@*":
    dependencies:
      "@docusaurus/logger": "*"
  autoprefixer@*:
    dependencies:
      colorette: "*"

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-4.11.0.cjs
