packageExtensions:
  "@graphql-markdown/core@*":
    dependencies:
      "@graphql-markdown/diff": "*"
  "@graphql-markdown/logger@*":
    dependencies:
      "@docusaurus/logger": "*"
  "@n1ru4l/graphql-live-query@*":
    dependencies:
      tslib: "*"
  autoprefixer@*:
    dependencies:
      colorette: "*"
  "@typescript-eslint/type-utils@*":
    dependencies:
      "@typescript-eslint/types": "*"

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-4.9.4.cjs
