packageExtensions:
  "@docusaurus/core@2.0.0-beta.9":
    dependencies:
      "@docusaurus/mdx-loader": 2.0.0-beta.9
  "@docusaurus/mdx-loader@2.0.0-beta.9":
    dependencies:
      tslib: "*"
  "@docusaurus/lqip-loader@2.0.0-beta.9":
    dependencies:
      tslib: "*"
  "@docusaurus/responsive-loader@1.4.0":
    dependencies:
      sharp: "*"
  "@graphql-eslint/eslint-plugin@2.4.0":
    dependencies:
      "@babel/code-frame": "*"
  autoprefixer@*:
    dependencies:
      colorette: "*"
  terser@*:
    dependencies:
      acorn: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.1.1.cjs

pnpEnableEsmLoader: true
