packageExtensions:
  "@n1ru4l/graphql-live-query@*":
    dependencies:
      tslib: "*"
  autoprefixer@*:
    dependencies:
      colorette: "*"

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-4.5.1.cjs
