ARG INTERCODE_TAG
FROM neinteractiveliterature/intercode:build-${INTERCODE_TAG}

USER root
RUN apt-get update && apt-get install -y --no-install-recommends s3cmd &&  && rm -rf /var/lib/apt/lists/*

USER www
RUN curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
RUN chmod +x ./cc-test-reporter
RUN ./cc-test-reporter before-build

RUN yarn install --production=false
RUN cp -R public/packs public/packs-test
