query OAuthAuthorizationPromptQuery($queryParams: Json!) {
  currentUser {
    id
  }
  oauthPreAuth(queryParams: $queryParams)
}

query OAuthAuthorizedApplicationQuery {
  myAuthorizedApplications {
    uid
    name
    scopes
  }
}
