mutation PurchaseTicket($ticketTypeId: Int!, $stripeToken: String!) {
  purchaseTicket(input: { ticket_type_id: $ticketTypeId, stripe_token: $stripeToken }) {
    ticket {
      id

      ticket_type {
        id
        description
      }

      payment_amount {
        fractional
      }
    }
  }
}
