#import "./queries.gql"

mutation StandaloneDropEvent($input: DropEventInput!) {
  dropEvent(input: $input) {
    event {
      id
      status
    }
  }
}

mutation StandaloneUpdateEvent($input: UpdateEventInput!) {
  updateEvent(input: $input) {
    event {
      ...StandaloneEditEvent_EventFields
    }
  }
}

mutation StandaloneCreateMaximumEventProvidedTicketsOverride($input: CreateMaximumEventProvidedTicketsOverrideInput!) {
  createMaximumEventProvidedTicketsOverride(input: $input) {
    maximum_event_provided_tickets_override {
      ...StandaloneEditEvent_MaximumEventProvidedTicketsOverrideFields
    }
  }
}

mutation StandaloneDeleteMaximumEventProvidedTicketsOverride($input: DeleteMaximumEventProvidedTicketsOverrideInput!) {
  deleteMaximumEventProvidedTicketsOverride(input: $input) {
    maximum_event_provided_tickets_override {
      ...StandaloneEditEvent_MaximumEventProvidedTicketsOverrideFields
    }
  }
}

mutation StandaloneUpdateMaximumEventProvidedTicketsOverride($input: UpdateMaximumEventProvidedTicketsOverrideInput!) {
  updateMaximumEventProvidedTicketsOverride(input: $input) {
    maximum_event_provided_tickets_override {
      ...StandaloneEditEvent_MaximumEventProvidedTicketsOverrideFields
    }
  }
}
