fragment CmsGraphqlQueryFields on CmsGraphqlQuery {
  id
  identifier
  query
  admin_notes
  current_ability_can_update
  current_ability_can_delete
}

query CmsGraphqlQueriesQuery {
  cmsGraphqlQueries {
    id
    ...CmsGraphqlQueryFields
  }

  currentAbility {
    can_create_cms_graphql_queries
  }
}
