#import "./queries.gql"

mutation CreateEventProposal($cloneEventProposalId: Int, $eventCategoryId: Int!) {
  createEventProposal(input: {
    clone_event_proposal_id: $cloneEventProposalId,
    event_category_id: $eventCategoryId
  }) {
    event_proposal {
      id
    }
  }
}

mutation UpdateEventProposal($input: UpdateEventProposalInput!) {
  updateEventProposal(input: $input) {
    event_proposal {
      id
      ...EventProposalFields
    }
  }
}

mutation DeleteEventProposal($id: Int!) {
  deleteEventProposal(input: { id: $id }) {
    clientMutationId
  }
}

mutation SubmitEventProposal($input: SubmitEventProposalInput!) {
  submitEventProposal(input: $input) {
    event_proposal {
      id
      ...EventProposalFields
    }
  }
}

mutation TransitionEventProposal($eventProposalId: Int!, $status: String!, $dropEvent: Boolean) {
  transitionEventProposal(input: { id: $eventProposalId, status: $status, drop_event: $dropEvent }) {
    event_proposal {
      id
      ...EventProposalFields
    }
  }
}

mutation UpdateEventProposalAdminNotes($eventProposalId: Int!, $adminNotes: String!) {
  updateEventProposalAdminNotes(input: { id: $eventProposalId, admin_notes: $adminNotes }) {
    event_proposal {
      id
      ...EventProposalFields
    }
  }
}
