fragment EventProposalFields on EventProposal {
  id
  title
  status
  form_response_attrs_json

  event_category {
    id
    name

    event_proposal_form {
      id
      form_api_json
    }
  }

  event {
    id
  }
}

fragment EventProposalFormData on Convention {
  starts_at
  ends_at
  timezone_name
  event_mailing_list_domain
}

query EventProposalQuery($eventProposalId: Int!) {
  convention {
    id
    ...EventProposalFormData
  }

  eventProposal(id: $eventProposalId) {
    ...EventProposalFields
  }
}

query EventProposalQueryWithOwner($eventProposalId: Int!) {
  convention {
    id
    ...EventProposalFormData
  }

  eventProposal(id: $eventProposalId) {
    ...EventProposalFields

    owner {
      id
      name
      email
    }
  }

  currentAbility {
    can_update_event_proposal(event_proposal_id: $eventProposalId)
    can_read_admin_notes_on_event_proposal(event_proposal_id: $eventProposalId)
  }
}

query EventProposalAdminNotesQuery($eventProposalId: Int!) {
  eventProposal(id: $eventProposalId) {
    id
    admin_notes
  }
}

query ProposeEventButtonQuery {
  myProfile {
    id

    user {
      id

      event_proposals {
        id
        title
        status
        created_at

        event_category {
          id
          name
        }

        convention {
          id
          name
        }
      }
    }
  }

  convention {
    event_categories {
      id
      name
      proposable
    }
  }
}
