/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  sidebar: [
    {
      type: 'doc',
      id: 'intro',
    },
    {
      type: 'category',
      label: 'Concepts',
      items: [
        {
          type: 'autogenerated',
          dirName: 'concepts',
        },
      ],
    },
    {
      type: 'category',
      label: 'GraphQL Schema Reference',
      items: [
        {
          type: 'autogenerated',
          dirName: 'graphql',
        },
      ],
    },
    {
      type: 'category',
      label: 'Liquid Reference',
      items: require('./docs/liquid/sidebar-schema.js').schemaSidebar,
    },
  ],
};
