# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in intercode_warp_core.gemspec
gemspec

gem "rake", "~> 13.0"

gem "rake-compiler"
gem "rb_sys"

gem "minitest", "~> 5.0"

gem "rubocop", "~> 1.21"
