fragment AdminDepartmentFields on Department {
  id
  name
  proposal_description

  event_categories {
    id
    name
  }
}

query DepartmentAdminQuery {
  currentAbility {
    can_update_departments
  }

  convention {
    id

    departments {
      ...AdminDepartmentFields
    }
  }
}
