#import "./queries.gql"

mutation CreateStaffPosition($input: CreateStaffPositionInput!) {
  createStaffPosition(input: $input) {
    staff_position {
      id
      ...StaffPositionFields
    }
  }
}

mutation UpdateStaffPosition($input: UpdateStaffPositionInput!) {
  updateStaffPosition(input: $input) {
    staff_position {
      id
      ...StaffPositionFields
    }
  }
}

mutation UpdateStaffPositionPermissions(
  $staffPositionId: Int!,
  $grantPermissions: [PermissionInput!]!,
  $revokePermissions: [PermissionInput!]!
) {
  updateStaffPositionPermissions(input: {
    staff_position_id: $staffPositionId,
    grant_permissions: $grantPermissions,
    revoke_permissions: $revokePermissions
  }) {
    staff_position {
      id
      ...StaffPositionFields
    }
  }
}

mutation DeleteStaffPosition($input: DeleteStaffPositionInput!) {
  deleteStaffPosition(input: $input) {
    staff_position {
      id
    }
  }
}
