fragment StaffPositionFields on StaffPosition {
  id
  name
  email
  visible

  user_con_profiles {
    id
    name_without_nickname
  }

  permissions {
    id
    permission

    model {
      __typename

      ...on Convention {
        id
        name
      }

      ...on EventCategory {
        id
        name
        default_color
      }
    }
  }
}

query StaffPositionsQuery {
  convention {
    id
    name

    event_categories {
      id
      name
      default_color
    }

    staff_positions {
      id
      ...StaffPositionFields
    }
  }
}
