fragment CommonConventionData on Convention {
  id
  name
  starts_at
  ends_at
  timezone_name
  event_category_keys
  ticket_name
}

fragment RunBasicSignupData on Run {
  confirmed_limited_signup_count
  not_counted_confirmed_signup_count
  waitlisted_signup_count

  my_signups {
    id
    state
  }
}

query CommonConventionDataQuery {
  convention {
    ...CommonConventionData
  }
}
