#import "./queries.gql"

mutation UpdateNotificationTemplate($eventKey: String!, $notificationTemplate: NotificationTemplateInput!) {
  updateNotificationTemplate(input: { event_key: $eventKey, notification_template: $notificationTemplate }) {
    notification_template {
      ...NotificationTemplateFields
    }
  }
}
