fragment NotificationTemplateFields on NotificationTemplate {
  id
  event_key
  subject
  body_html
  body_text

  notification_context {
    __typename

    ...on EventCategory {
      id
      name
    }
  }
}

query NotificationAdminQuery {
  convention {
    id

    event_categories {
      id
      name
    }

    notification_templates {
      ...NotificationTemplateFields
    }
  }
}
