#import "./queries.gql"
#import "../queries.gql"
#import "../EventPage/queries.gql"

mutation ChangeSignupBucket($signupId: Int!, $bucketKey: String!) {
  updateSignupBucket(input: { id: $signupId, bucket_key: $bucketKey }) {
    signup {
      id
      ...SignupFields

      run {
        id
        ...EventPageRunFields
        ...RunBasicSignupData
      }
    }
  }
}

mutation ForceConfirmSignup($signupId: Int!, $bucketKey: String!) {
  forceConfirmSignup(input: { id: $signupId, bucket_key: $bucketKey }) {
    signup {
      id
      ...SignupFields

      run {
        id
        ...EventPageRunFields
        ...RunBasicSignupData
      }
    }
  }
}

mutation UpdateSignupCounted($signupId: Int!, $counted: Boolean!) {
  updateSignupCounted(input: { id: $signupId, counted: $counted }) {
    signup {
      id
      ...SignupFields

      run {
        id
        ...EventPageRunFields
        ...RunBasicSignupData
      }
    }
  }
}

mutation WithdrawAllUserConProfileSignups($userConProfileId: Int!) {
  withdrawAllUserConProfileSignups(input: { user_con_profile_id: $userConProfileId }) {
    user_con_profile {
      id

      ...UserConProfileSignupsFragment
    }
  }
}
