fragment LiquidAssignFields on LiquidAssign {
  name
  drop_class_name
  cms_variable_value_json
}

query LiquidAssignsQuery {
  liquidAssigns {
    ...LiquidAssignFields
  }
}

query NotifierLiquidAssignsQuery($eventKey: String!) {
  liquidAssigns: notifierLiquidAssigns(eventKey: $eventKey) {
    ...LiquidAssignFields
  }
}
