#import "./queries.gql"

mutation CreateUserActivityAlert(
  $userActivityAlert: UserActivityAlertInput!,
  $notificationDestinations: [NotificationDestinationInput!]!,
) {
  createUserActivityAlert(input: {
    user_activity_alert: $userActivityAlert,
    notification_destinations: $notificationDestinations
  }) {
    user_activity_alert {
      id
      ...UserActivityAlertFields
    }
  }
}

mutation UpdateUserActivityAlert(
  $id: Int!,
  $userActivityAlert: UserActivityAlertInput!,
  $addNotificationDestinations: [NotificationDestinationInput!]!,
  $removeNotificationDestinationIds: [Int!]!
) {
  updateUserActivityAlert(input: {
    id: $id,
    user_activity_alert: $userActivityAlert,
    add_notification_destinations: $addNotificationDestinations,
    remove_notification_destination_ids: $removeNotificationDestinationIds
  }) {
    user_activity_alert {
      id
      ...UserActivityAlertFields
    }
  }
}

mutation DeleteUserActivityAlert($id: Int!) {
  deleteUserActivityAlert(input: { id: $id }) {
    user_activity_alert {
      id
      ...UserActivityAlertFields
    }
  }
}
