fragment UserActivityAlertsAdminConventionFields on Convention {
  id
  ticket_name
  ticket_mode

  staff_positions {
    id
    name
  }
}

fragment UserActivityAlertFields on UserActivityAlert {
  id
  email
  partial_name
  trigger_on_user_con_profile_create
  trigger_on_ticket_create
  user {
    id
    name
  }

  notification_destinations {
    id

    staff_position {
      id
      name
    }

    user_con_profile {
      id
      name_without_nickname
    }
  }
}

query ConventionTicketNameQuery {
  convention {
    id
    ...UserActivityAlertsAdminConventionFields
  }
}

query UserActivityAlertQuery($id: Int!) {
  convention {
    id
    ...UserActivityAlertsAdminConventionFields

    user_activity_alert(id: $id) {
      id
      ...UserActivityAlertFields
    }
  }
}

query UserActivityAlertsAdminQuery {
  convention {
    id
    ticket_name
    ticket_mode

    user_activity_alerts {
      id
      ...UserActivityAlertFields
    }
  }
}
