fragment UserActivityAlertFields on UserActivityAlert {
  id
  email
  partial_name
  trigger_on_user_con_profile_create
  trigger_on_ticket_create
  user {
    id
    name
  }

  alert_destinations {
    id

    staff_position {
      id
      name
    }

    user_con_profile {
      id
      name_without_nickname
    }
  }
}

query UserActivityAlertQuery($id: Int!) {
  convention {
    id
    ticket_name

    staff_positions {
      id
      name
    }

    user_activity_alert(id: $id) {
      ...UserActivityAlertFields
    }
  }
}

query UserActivityAlertsAdminQuery {
  convention {
    id
    ticket_name

    user_activity_alerts {
      ...UserActivityAlertFields
    }
  }
}

mutation CreateUserActivityAlert(
  $userActivityAlert: UserActivityAlertInput!,
  $alertDestinations: [AlertDestinationInput!],
) {
  createUserActivityAlert(input: {
    user_activity_alert: $userActivityAlert,
    alert_destinations: $alertDestinations
  }) {
    user_activity_alert {
      ...UserActivityAlertFields
    }
  }
}

mutation UpdateUserActivityAlert(
  $id: Int!,
  $userActivityAlert: UserActivityAlertInput!,
  $addAlertDestinations: [AlertDestinationInput!]!,
  $removeAlertDestinationIds: [Int!]!
) {
  updateUserActivityAlert(input: {
    id: $id,
    user_activity_alert: $userActivityAlert,
    add_alert_destinations: $addAlertDestinations,
    remove_alert_destination_ids: $removeAlertDestinationIds
  }) {
    user_activity_alert {
      ...UserActivityAlertFields
    }
  }
}

mutation DeleteUserActivityAlert($id: Int!) {
  deleteUserActivityAlert(input: { id: $id }) {
    user_activity_alert {
      ...UserActivityAlertFields
    }
  }
}
