Time::DATE_FORMATS[:long_with_weekday] = "%A, %B %-d, %Y at %l:%M%P"
Time::DATE_FORMATS[:date_only] = "%B %-d, %Y"
Time::DATE_FORMATS[:date_only_with_weekday] = "%A, %B %-d, %Y"
Time::DATE_FORMATS[:long_weekday_with_time] = "%A at %l:%M%P"
Time::DATE_FORMATS[:short_weekday_with_time] = "%a %l:%M%P"
