#import "./queries.gql"

mutation CreateTicketType($input: CreateTicketTypeInput!) {
  createTicketType(input: $input) {
    ticket_type {
      id
      ...TicketTypeAdmin_TicketTypeFields
    }
  }
}

mutation UpdateTicketType($input: UpdateTicketTypeInput!) {
  updateTicketType(input: $input) {
    ticket_type {
      id
      ...TicketTypeAdmin_TicketTypeFields
    }
  }
}

mutation DeleteTicketType($input: DeleteTicketTypeInput!) {
  deleteTicketType(input: $input) {
    ticket_type {
      id
    }
  }
}
