#import "../Store/pricingStructureFields.gql"

fragment TicketTypeAdmin_TicketTypeFields on TicketType {
  id
  name
  description
  publicly_available
  counts_towards_convention_maximum
  allows_event_signups
  maximum_event_provided_tickets

  pricing_schedule {
    timespans {
      start
      finish
      value {
        fractional
        currency_code
      }
    }
  }

  providing_products {
    id
    name
    available

    pricing_structure {
      ...PricingStructureFields
    }
  }
}

query AdminTicketTypesQuery {
  convention {
    id
    ticket_types {
      id
      ...TicketTypeAdmin_TicketTypeFields
    }

    ticket_name
    timezone_name
  }
}
