fragment SignupFields on Signup {
  id
  state
  counted
  bucket_key
  requested_bucket_key

  run {
    title_suffix
    starts_at
    ends_at

    rooms {
      name
    }

    event {
      title
      team_member_name

      registration_policy {
        buckets {
          key
          name
          anything
        }
      }

      team_members {
        user_con_profile {
          id
        }
      }
    }
  }

  user_con_profile {
    id
    name_without_nickname
    nickname
    birth_date
    email
    address
    city
    state
    zipcode
    country
    day_phone
    evening_phone
    best_call_time
    preferred_contact
  }
}

query SignupAdminEventQuery($eventId: Int!) {
  event(id: $eventId) {
    id
    title
  }
}

query AdminSignupQuery($id: Int!) {
  convention {
    timezone_name
  }

  myProfile {
    id
    ability {
      can_update_signup(signup_id: $id)
    }
  }

  signup(id: $id) {
    ...SignupFields
  }
}

query RunSignupsTableSignupsQuery($eventId: Int!, $runId: Int!, $page: Int, $perPage: Int, $filters: SignupFiltersInput, $sort: [SortInput]) {
  event(id: $eventId) {
    id
    team_member_name

    team_members {
      id

      user_con_profile {
        id
      }
    }

    registration_policy {
      buckets {
        key
        name
      }
    }

    run(id: $runId) {
      id

      signups_paginated(page: $page, per_page: $perPage, filters: $filters, sort: $sort) {
        total_entries
        total_pages
        current_page
        per_page

        entries {
          id
          state
          counted
          bucket_key
          requested_bucket_key

          run {
            starts_at
          }

          user_con_profile {
            id
            name_inverted
            name_without_nickname
            email
            birth_date
          }
        }
      }
    }
  }
}
