fragment AdminOrderFieldsFragment on Order {
  id
  status
  submitted_at
  charge_id
  payment_note

  user_con_profile {
    id
    name_without_nickname
  }

  total_price {
    fractional
    currency_code
  }

  payment_amount {
    fractional
    currency_code
  }

  order_entries {
    id
    quantity
    describe_products

    product {
      id
      name
    }

    product_variant {
      id
      name
    }

    price_per_item {
      fractional
      currency_code
    }
  }
}

fragment CouponApplicationFields on CouponApplication {
  id

  discount {
    fractional
    currency_code
  }

  coupon {
    id
    code
    fixed_amount {
      fractional
      currency_code
    }
    percent_discount
    provides_product {
      id
      name
    }
  }
}

fragment CartOrderFields on Order {
  id

  coupon_applications {
    ...CouponApplicationFields
  }

  total_price_before_discounts {
    fractional
    currency_code
  }

  total_price {
    fractional
    currency_code
  }

  order_entries {
    id
    ...OrderEntryFields
  }
}
