#import './pricingStructureFields.gql'
#import './orderFields.gql'

fragment AdminProductFields on Product {
  id
  name
  description
  description_html
  image_url
  available
  payment_options

  pricing_structure {
    ...PricingStructureFields
  }

  product_variants {
    id
    name
    description
    image_url
    position

    override_pricing_structure {
      ...PricingStructureFields
    }
  }
}

fragment OrderEntryFields on OrderEntry {
  id
  quantity

  product {
    id
    name
    payment_options
    provides_ticket_type {
      id
    }
  }

  product_variant {
    id
    name
  }

  price {
    fractional
    currency_code
  }

  price_per_item {
    fractional
    currency_code
  }
}

query AdminOrdersQuery($page: Int, $perPage: Int, $filters: OrderFiltersInput, $sort: [SortInput!]) {
  currentAbility {
    can_update_orders
  }

  convention {
    id
    timezone_name

    orders_paginated(page: $page, per_page: $perPage, filters: $filters, sort: $sort) {
      current_page
      per_page
      total_pages

      entries {
        id
        ...AdminOrderFieldsFragment
      }
    }
  }
}

query AdminProductsQuery {
  convention {
    id
    products {
      id
      ...AdminProductFields
    }
  }

  currentAbility {
    can_update_products
  }
}

query AdminStoreAbilityQuery {
  currentAbility {
    can_update_products
    can_update_orders
  }

  convention {
    id
    timezone_name
  }
}

query CartQuery {
  myProfile {
    id
    name_without_nickname
  }

  convention {
    id
    name
  }

  currentPendingOrder {
    id

    order_entries {
      id
      ...OrderEntryFields
    }
  }
}

query OrderHistoryQuery {
  convention {
    id
    name
    timezone_name

    staff_positions {
      id
      name
      email
    }
  }

  myProfile {
    id
    name_without_nickname

    orders {
      id
      status
      submitted_at

      total_price {
        fractional
        currency_code
      }

      payment_amount {
        fractional
        currency_code
      }

      order_entries {
        id
        quantity

        product {
          id
          name
          image_url
          payment_options
        }

        product_variant {
          id
          name
          image_url
        }

        price_per_item {
          fractional
          currency_code
        }

        price {
          fractional
          currency_code
        }
      }
    }
  }
}

query OrderSummaryQuery {
  convention {
    id
    products {
      id
      name

      order_quantities_by_status {
        status
        quantity
      }

      product_variants {
        id
        name

        order_quantities_by_status {
          status
          quantity
        }
      }
    }
  }
}

query OrderFormProductQuery($productId: Int!) {
  currentUser {
    id
  }

  product(id: $productId) {
    id
    image_url
    name
    pricing_structure {
      ...PricingStructureFields
    }
    description_html
    provides_ticket_type {
      id
    }

    product_variants {
      id
      name
      position
      override_pricing_structure {
        ...PricingStructureFields
      }
    }
  }
}
