#import "./queries.gql"

mutation CreateNavigationItem($navigationItem: CmsNavigationItemInput!) {
  createCmsNavigationItem(input: { cms_navigation_item: $navigationItem }) {
    cms_navigation_item {
      id
      ...AdminNavigationItemFields
    }
  }
}

mutation UpdateNavigationItem($id: Int!, $navigationItem: CmsNavigationItemInput!) {
  updateCmsNavigationItem(input: { id: $id, cms_navigation_item: $navigationItem }) {
    cms_navigation_item {
      id
      ...AdminNavigationItemFields
    }
  }
}

mutation DeleteNavigationItem($id: Int!) {
  deleteCmsNavigationItem(input: { id: $id }) {
    cms_navigation_item {
      id
    }
  }
}

mutation SortNavigationItems($sortItems: [UpdateCmsNavigationItemInput!]!) {
  sortCmsNavigationItems(input: { sort_items: $sortItems }) {
    clientMutationId
  }
}
