fragment AdminNavigationItemFields on CmsNavigationItem {
  id
  position
  title

  page {
    id
  }

  navigation_section {
    id
  }
}

query NavigationItemsAdminQuery {
  convention {
    id
    name
  }

  cmsPages {
    id
    name
  }

  cmsNavigationItems {
    id
    ...AdminNavigationItemFields
  }
}
