groups:
  default:
    concurrency: 5
    queues:
      - default
  mailers:
    concurrency: 5
    queues:
      - mailers
  ahoy:
    concurrency: 5
    queues:
      - ahoy
  cloudwatch_scheduler:
    concurrency: 1
    queues:
      - cloudwatch_scheduler
timeout: 2
