#import './queries.gql'

mutation CreateCmsFile($file: Upload!) {
  createCmsFile(input: { file: $file }) {
    cms_file {
      ...CmsFileFields
    }
  }
}

mutation RenameCmsFile($id: Int!, $filename: String!) {
  renameCmsFile(input: { id: $id, filename: $filename }) {
    cms_file {
      ...CmsFileFields
    }
  }
}

mutation DeleteCmsFile($id: Int!) {
  deleteCmsFile(input: { id: $id }) {
    clientMutationId
  }
}
