fragment CmsFileFields on CmsFile {
  id
  filename
  url
  content_type
  size
  current_ability_can_delete
}

query CmsFilesAdminQuery {
  convention {
    id
    name
  }

  currentAbility {
    can_create_cms_files
  }

  cmsFiles {
    ...CmsFileFields
  }
}
