// Generated by typed-scss-modules
export declare const bucketAvailabilityCell: string;
export declare const bucketAvailabilityDisplay: string;
export declare const bucketAvailabilityDisplayCompact: string;
export declare const bucketAvailabilityOpenSlot: string;
