// Generated by typed-scss-modules
export declare const formEditor: string;
export declare const formEditorItem: string;
export declare const formEditorItemIdentifier: string;
export declare const formEditorItemOverlay: string;
export declare const formEditorTopNavbar: string;
export declare const formItemEditor: string;
export declare const formItemEditorContent: string;
export declare const formItemEditorError: string;
export declare const formItemEditorPreview: string;
export declare const formItemEditorTools: string;
export declare const formSectionEditorAddItemBar: string;
export declare const formSectionEditorContent: string;
export declare const formSectionEditorNav: string;
