// Generated by typed-scss-modules
export declare const maximumEventSignups1: string;
export declare const maximumEventSignups1Transition: string;
export declare const maximumEventSignups2: string;
export declare const maximumEventSignups2Transition: string;
export declare const maximumEventSignups3: string;
export declare const maximumEventSignups3Transition: string;
export declare const maximumEventSignups4: string;
export declare const maximumEventSignups4Transition: string;
export declare const maximumEventSignups5: string;
export declare const maximumEventSignups5Transition: string;
export declare const maximumEventSignups6: string;
export declare const maximumEventSignups6Transition: string;
export declare const maximumEventSignupsNotNow: string;
export declare const maximumEventSignupsNotNowTransition: string;
export declare const maximumEventSignupsNotYet: string;
export declare const maximumEventSignupsUnlimited: string;
export declare const maximumEventSignupsUnlimitedTransition: string;
