// Generated by typed-scss-modules
export declare const siteSearch: string;
export declare const siteSearchEnterActive: string;
export declare const siteSearchEnterDone: string;
export declare const siteSearchExitActive: string;
export declare const siteSearchExitDone: string;
export declare const siteSearchFadeAndExpand: string;
export declare const siteSearchNavigationButton: string;
export declare const siteSearchNavigationButtonEnterActive: string;
export declare const siteSearchNavigationButtonEnterDone: string;
export declare const siteSearchNavigationButtonExitActive: string;
export declare const siteSearchNavigationButtonExitDone: string;
export declare const siteSearchNavigationButtonFade: string;
