query AppRootQuery($path: String!) {
  effectiveCmsLayout(path: $path) {
    id
    content_html
  }

  currentUser {
    id
    name
  }

  currentPendingOrder {
    id
    order_entries {
      id
      quantity
    }
  }

  myProfile {
    id
    name
    accepted_clickwrap_agreement
    name_without_nickname
    first_name
    last_name
    ticket {
      id
    }
  }

  assumedIdentityFromProfile {
    id
    name_without_nickname
  }

  convention {
    id
    name
    site_mode
    signup_mode
    timezone_name
    clickwrap_agreement
  }

  rootSite {
    id
    site_name
  }

  cmsNavigationItems {
    id
    position
    title

    navigation_section {
      id
    }

    page {
      id
      slug
    }
  }
}
