#import "../queries.gql"

fragment TeamMemberTicketFields on Ticket {
  id

  user_con_profile {
    id
  }

  ticket_type {
    id
    name
  }

  provided_by_event {
    id
    title
  }
}

fragment TeamMemberUserConProfileFields on UserConProfile {
  id
  name_without_nickname
  name_inverted
  email
  mobile_phone

  ticket {
    id
    ...TeamMemberTicketFields
  }
}

fragment TeamMemberUserConProfileSearchFields on UserConProfile {
  id
  name_without_nickname
  name_inverted
  email

  ticket {
    id
    ...TeamMemberTicketFields
  }
}

fragment TeamMemberFields on TeamMember {
  id
  display_team_member
  show_email
  receive_con_email
  receive_signup_email

  user_con_profile {
    id
    ...TeamMemberUserConProfileFields
  }
}

fragment TeamMemberFieldsWithoutPersonalInfo on TeamMember {
  id
  display_team_member
  show_email
  receive_con_email
  receive_signup_email

  user_con_profile {
    id
    ...TeamMemberUserConProfileSearchFields
  }
}

query TeamMembersQuery($eventId: Int!) {
  convention {
    id
    ...CommonConventionData

    ticket_types {
      id
      name
      description
      maximum_event_provided_tickets(event_id: $eventId)
    }

    ticket_name
  }

  event(id: $eventId) {
    id
    title

    event_category {
      id
      can_provide_tickets
      team_member_name
    }

    provided_tickets {
      id
      ...TeamMemberTicketFields
    }

    team_members {
      id
      ...TeamMemberFields

      user_con_profile {
        id
        day_phone
        evening_phone
        best_call_time
        preferred_contact
        email
      }
    }
  }
}

query TeamMemberUserConProfilesQuery($name: String) {
  convention {
    id
    user_con_profiles_paginated(filters: { name: $name }, per_page: 50) {
      entries {
        id
        ...TeamMemberUserConProfileSearchFields
      }
    }
  }
}
