#import "./queries.gql"

mutation CreateFormWithJSON($formJSON: String!, $formType: FormType!) {
  createFormWithJSON(input: { form_json: $formJSON, form_type: $formType }) {
    form {
      id
      ...FormFields
    }
  }
}

mutation UpdateFormWithJSON($id: Int!, $formJSON: String!) {
  updateFormWithJSON(input: { id: $id, form_json: $formJSON }) {
    form {
      id
      ...FormFields
    }
  }
}

mutation DeleteForm($id: Int!) {
  deleteForm(input: { id: $id }) {
    clientMutationId
  }
}

mutation CreateFormItem($formSectionId: Int!, $formItem: FormItemInput!) {
  createFormItem(input: { form_section_id: $formSectionId, form_item: $formItem }) {
    form_item {
      id
      ...FormEditorFormItemFields
    }
  }
}

mutation UpdateFormItem($id: Int!, $formItem: FormItemInput!) {
  updateFormItem(input: { id: $id, form_item: $formItem }) {
    form_item {
      id
      ...FormEditorFormItemFields
    }
  }
}

mutation MoveFormItem($id: Int!, $formSectionId: Int!, $destinationIndex: Int) {
  moveFormItem(input: { id: $id, form_section_id: $formSectionId, destination_index: $destinationIndex }) {
    form_section {
      id
      ...FormEditorFormSectionFields
    }
  }
}
