fragment FormFields on Form {
  id
  title
  form_type
  export_json

  event_categories {
    id
    name
  }

  proposal_event_categories {
    id
    name
  }

  user_con_profile_conventions {
    id
    name
  }
}

fragment FormEditorFormItemFields on FormItem {
  id
  position
  identifier
  item_type
  admin_description
  public_description
  properties
  rendered_properties
  default_value
}

fragment FormEditorData on Form {
  id
  title
  form_type

  form_sections {
    id
    title
    position
    form_items {
      ...FormEditorFormItemFields
    }
  }
}

query FormAdminQuery {
  convention {
    id
    name

    forms {
      id
      ...FormFields
    }
  }
}

query FormEditorQuery($id: Int!) {
  convention {
    id
    name
    starts_at
    ends_at
    timezone_name
    event_mailing_list_domain
  }

  form(id: $id) {
    ...FormEditorData
  }
}

query PreviewFormItemQuery($formSectionId: Int!, $formItem: FormItemInput!) {
  previewFormItem(formSectionId: $formSectionId, formItem: $formItem) {
    id
    ...FormEditorFormItemFields
  }
}
