fragment CmsPageAdminLayoutFields on CmsLayout {
  id
  name
}

fragment CmsPageFields on Page {
  id
  name
  slug
  content
  admin_notes
  skip_clickwrap_agreement
  hidden_from_search
  current_ability_can_update
  current_ability_can_delete

  cms_layout {
    ...CmsPageAdminLayoutFields
  }
}

query CmsPagesAdminQuery {
  convention {
    id
    name
  }

  currentAbility {
    can_create_pages
  }

  cmsPages {
    ...CmsPageFields
  }

  cmsParent {
    ...on RootSite {
      id

      default_layout {
        ...CmsPageAdminLayoutFields
      }
    }

    ...on Convention {
      id

      default_layout {
        ...CmsPageAdminLayoutFields
      }
    }
  }

  cmsLayouts {
    ...CmsPageAdminLayoutFields
  }
}
