fragment CmsPageFields on Page {
  id
  name
  slug
  content
  admin_notes
  skip_clickwrap_agreement

  cms_layout {
    ...CmsLayoutFields
  }
}

fragment CmsLayoutFields on CmsLayout {
  id
  name
}

query CmsPagesAdminQuery {
  cmsPages {
    ...CmsPageFields
  }

  cmsParent {
    ...on RootSite {
      id

      default_layout {
        ...CmsLayoutFields
      }
    }

    ...on Convention {
      id

      default_layout {
        ...CmsLayoutFields
      }
    }
  }

  cmsLayouts {
    ...CmsLayoutFields
  }
}
