#import "./queries.gql"

mutation MergeUsers($userIds: [Int!]!, $winningUserId: Int!, $winningUserConProfiles: [WinningUserConProfileInput!]!) {
  mergeUsers(input: { userIds: $userIds, winningUserId: $winningUserId, winningUserConProfiles: $winningUserConProfiles }) {
    user {
      ...DetailedUserFields
    }
  }
}
