query UsersTableUsersQuery($page: Int, $perPage: Int, $filters: UserFiltersInput, $sort: [SortInput!]) {
  users_paginated(page: $page, per_page: $perPage, filters: $filters, sort: $sort) {
    total_entries
    total_pages
    current_page
    per_page

    entries {
      id
      name_inverted
      first_name
      last_name
      email
      privileges
    }
  }

  currentAbility {
    can_create_user_con_profiles
  }
}

fragment DetailedUserFields on User {
  id
  name
  first_name
  last_name
  email
  privileges

  user_con_profiles {
    id

    convention {
      id
      name
      domain
      starts_at
      ticket_name
      timezone_name
    }

    staff_positions {
      id
      name
    }
  }
}

query UserAdminQuery($id: Int!) {
  user(id: $id) {
    ...DetailedUserFields
  }
}

query MergeUsersModalQuery($ids: [Int!]!) {
  users(ids: $ids) {
    ...DetailedUserFields
  }
}
