Feature: Reports Generated by Intercode

  Scenario: Per User Report
    Given I am Staff
    When I select the ‘Per User Report’
    Then I should see a formatted list of all users and statuses

  Scenario: Printing Per User Report
    Given I am Staff
    When I print the ‘Per User Report’
    Then CSS should print each user on a separate page

  Scenario: Per Room Report
    Given I am Staff
    When I select the ‘Per Room Report’
    Then I should see a list of all rooms occupied by date/time

  Scenario: Printing Per Room Report
    Given I am Staff
    When I print the ‘Per Room Report’
    Then CSS should print each user on a separate page

  Scenario: Per Game Report
    Given I am Staff
    When I select the ‘Per Game Report’
    Then I should see a list of all games with users signed up

  Scenario: Printing Per Game Report
    Given I am Staff
    When I print the ‘Per Game Report’
    Then CSS should print each user on a separate page

  Scenario: Volunteer Report
    Given I am Staff
    When I select ‘Volunteer Report’
    Then I should see a list of all volunteers signed up per slot

  Scenario: ‘Who’s Not Playing’ Report
    Given I am Staff
    When I select ‘Not Playing Report’
    Then I should see a list of all users not signed up for an event during a range of hours
