#import './queries.gql'

mutation CreateContentGroup($cmsContentGroup: CmsContentGroupInput!) {
  createCmsContentGroup(input: { cms_content_group: $cmsContentGroup }) {
    cms_content_group {
      ...CmsContentGroupFields
    }
  }
}

mutation UpdateContentGroup($id: Int!, $cmsContentGroup: CmsContentGroupInput!) {
  updateCmsContentGroup(input: { id: $id, cms_content_group: $cmsContentGroup }) {
    cms_content_group {
      ...CmsContentGroupFields
    }
  }
}

mutation DeleteContentGroup($id: Int!) {
  deleteCmsContentGroup(input: { id: $id }) {
    clientMutationId
  }
}
