#import './queries.gql'

mutation CreateContentGroup($cmsContentGroup: CmsContentGroupInput!, $permissions: [PermissionInput!]) {
  createCmsContentGroup(input: { cms_content_group: $cmsContentGroup, permissions: $permissions }) {
    cms_content_group {
      ...CmsContentGroupFields
    }
  }
}

mutation UpdateContentGroup($id: Int!, $cmsContentGroup: CmsContentGroupInput!, $grantPermissions: [PermissionInput!], $revokePermissions: [PermissionInput!]) {
  updateCmsContentGroup(input: { id: $id, cms_content_group: $cmsContentGroup, grant_permissions: $grantPermissions, revoke_permissions: $revokePermissions }) {
    cms_content_group {
      ...CmsContentGroupFields
    }
  }
}

mutation DeleteContentGroup($id: Int!) {
  deleteCmsContentGroup(input: { id: $id }) {
    clientMutationId
  }
}
