fragment CmsContentFields on CmsContent {
  __typename

  ...on Page {
    id
    name
  }

  ...on CmsPartial {
    id
    name
  }

  ...on CmsLayout {
    id
    name
  }
}

fragment CmsContentGroupFields on CmsContentGroup {
  id
  name

  contents {
    ...CmsContentFields
  }
}

query CmsContentGroupsAdminQuery {
  convention {
    id
    name
  }

  cmsContentGroups {
    ...CmsContentGroupFields
  }
}

query SearchCmsContentQuery($name: String) {
  searchCmsContent(name: $name) {
    ...CmsContentFields
  }
}
