#import "../../Permissions/fragments.gql"

fragment CmsContentFields on CmsContent {
  __typename

  ...on Page {
    id
    name
  }

  ...on CmsPartial {
    id
    name
  }

  ...on CmsLayout {
    id
    name
  }
}

fragment CmsContentGroupFields on CmsContentGroup {
  id
  name
  current_ability_can_update
  current_ability_can_delete

  contents {
    ...CmsContentFields
  }

  permissions {
    id
    permission

    role {
      ...PermissionedRoleFields
    }
  }
}

query CmsContentGroupsAdminQuery {
  convention {
    id
    name

    staff_positions {
      id
      name
    }
  }

  cmsContentGroups {
    ...CmsContentGroupFields
  }

  currentAbility {
    can_create_cms_content_groups
  }
}

query SearchCmsContentQuery($name: String) {
  searchCmsContent(name: $name) {
    ...CmsContentFields
  }
}
