#import '../Store/adminProductFields.gql'
#import '../Store/orderFields.gql'

fragment UserConProfileFields on UserConProfile {
  id
  name
  privileges
  form_response_attrs_json
  gravatar_enabled
  gravatar_url
}

fragment UserConProfileFormData on Convention {
  id
  starts_at
  ends_at
  timezone_name

  user_con_profile_form {
    id
    form_api_json
  }
}

query UserConProfileQuery($id: Int!) {
  convention {
    ...UserConProfileFormData

    id
  }

  userConProfile(id: $id) {
    id
    ...UserConProfileFields
  }
}

fragment UserConProfileAdminTicketFields on Ticket {
  id
  created_at
  updated_at

  order_entry {
    id

    order {
      ...AdminOrderFieldsFragment
    }

    price_per_item {
      fractional
      currency_code
    }
  }

  ticket_type {
    id
    description
    name
  }

  provided_by_event {
    id
    title
  }
}

query UserConProfileAdminQuery($id: Int!) {
  myProfile {
    id
    ability {
      can_read_signups
      can_update_user_con_profile(user_con_profile_id: $id)
      can_delete_user_con_profile(user_con_profile_id: $id)
      can_become_user_con_profile(user_con_profile_id: $id)
    }
  }

  convention {
    id
    name
    starts_at
    ends_at
    timezone_name
    ticket_name
    ticket_mode

    user_con_profile_form {
      id
      form_api_json
    }

    ticket_types {
      id
      description
      name
      publicly_available
      maximum_event_provided_tickets

      providing_products {
        ...AdminProductFields
      }
    }
  }

  userConProfile(id: $id) {
    id
    email
    user_id
    name
    name_without_nickname
    form_response_attrs_json
    gravatar_enabled
    gravatar_url

    ticket {
      id
      ...UserConProfileAdminTicketFields
    }
  }
}

query ConvertToEventProvidedTicketQuery($eventId: Int!) {
  convention {
    id
    ticket_name

    ticket_types {
      id
      maximum_event_provided_tickets(event_id: $eventId)
      description
      name
    }
  }

  event(id: $eventId) {
    id
    title

    event_category {
      id
      can_provide_tickets
    }

    provided_tickets {
      id
      ticket_type {
        id
      }
    }
  }
}

query UserConProfilesTableUserConProfilesQuery($page: Int, $perPage: Int, $filters: UserConProfileFiltersInput, $sort: [SortInput!]) {
  convention {
    id
    name
    starts_at
    ends_at
    timezone_name
    ticket_name
    ticket_mode

    ticket_types {
      id
      name
    }

    user_con_profile_form {
      id
      form_api_json
    }

    user_con_profiles_paginated(page: $page, per_page: $perPage, filters: $filters, sort: $sort) {
      total_entries
      total_pages
      current_page
      per_page

      entries {
        id
        name_inverted
        first_name
        last_name
        email
        privileges
        form_response_attrs_json
        order_summary
        gravatar_enabled
        gravatar_url

        user_id

        team_members {
          id
        }

        ticket {
          id
          updated_at

          order_entry {
            price_per_item {
              fractional
              currency_code
            }
          }

          ticket_type {
            id
            name
          }
        }
      }
    }
  }

  currentAbility {
    can_create_user_con_profiles
  }
}

query AddAttendeeUsersQuery($name: String) {
  users_paginated(filters: { name: $name }, per_page: 50) {
    entries {
      id
      name
      email
      first_name
      last_name
    }
  }
}

query AddAttendeeUserConProfileFormQuery {
  convention {
    id

    user_con_profile_form {
      id
      form_api_json
    }
  }
}

query TicketAdminWithoutTicketAbilityQuery {
  currentAbility {
    can_create_tickets
  }
}

query TicketAdminWithTicketAbilityQuery($ticketId: Int!) {
  currentAbility {
    can_create_tickets
    can_update_ticket(ticket_id: $ticketId)
    can_delete_ticket(ticket_id: $ticketId)
  }
}
