fragment UserConProfileFields on UserConProfile {
  id
  name
  privileges
  form_response_attrs_json
}

fragment UserConProfileFormData on Convention {
  starts_at
  ends_at
  timezone_name

  user_con_profile_form {
    id
    form_api_json
  }
}

query UserConProfileQuery($id: Int!) {
  currentAbility {
    can_update_privileges_user_con_profile(user_con_profile_id: $id)
  }

  convention {
    ...UserConProfileFormData

    id
    privilege_names
    mail_privilege_names
  }

  userConProfile(id: $id) {
    ...UserConProfileFields
  }
}

query MyProfileQuery {
  convention {
    ...UserConProfileFormData
  }

  myProfile {
    ...UserConProfileFields
  }
}

fragment UserConProfileAdminTicketFields on Ticket {
  id
  charge_id
  payment_note
  created_at
  updated_at

  payment_amount {
    fractional
    currency_code
  }

  ticket_type {
    id
    description
    name
  }

  provided_by_event {
    id
    title
  }
}

query UserConProfileAdminQuery($id: Int!) {
  myProfile {
    id
    ability {
      can_read_signups
      can_update_user_con_profile(user_con_profile_id: $id)
      can_update_privileges_user_con_profile(user_con_profile_id: $id)
      can_delete_user_con_profile(user_con_profile_id: $id)
      can_become_user_con_profile(user_con_profile_id: $id)
    }
  }

  convention {
    id
    name
    starts_at
    ends_at
    timezone_name
    ticket_name

    user_con_profile_form {
      id
      form_api_json
    }
  }

  userConProfile(id: $id) {
    id
    name
    name_without_nickname
    privileges
    form_response_attrs_json

    ticket {
      ...UserConProfileAdminTicketFields
    }
  }
}

query ConvertToEventProvidedTicketQuery($eventId: Int!) {
  convention {
    id
    ticket_name

    ticket_types {
      id
      maximum_event_provided_tickets(event_id: $eventId)
      description
      name
    }
  }

  event(id: $eventId) {
    id
    title

    event_category {
      id
      can_provide_tickets
    }

    provided_tickets {
      id
      ticket_type {
        id
      }
    }
  }
}

query UserConProfilesTableUserConProfilesQuery($page: Int, $perPage: Int, $filters: UserConProfileFiltersInput, $sort: [SortInput]) {
  convention {
    id
    name
    privilege_names
    starts_at
    ends_at
    timezone_name
    ticket_name

    ticket_types {
      id
      name
    }

    user_con_profile_form {
      id
      form_api_json
    }

    user_con_profiles_paginated(page: $page, per_page: $perPage, filters: $filters, sort: $sort) {
      total_entries
      total_pages
      current_page
      per_page

      entries {
        id
        name_inverted
        first_name
        last_name
        email
        privileges
        form_response_attrs_json
        order_summary

        team_members {
          id
        }

        ticket {
          id
          updated_at

          payment_amount {
            fractional
            currency_code
          }

          ticket_type {
            id
            name
          }
        }
      }
    }
  }

  currentAbility {
    can_create_user_con_profiles
  }
}
