#import '../couponFields.gql'

fragment AdminCouponFields on Coupon {
  ...CouponFields
  usage_limit
  expires_at
}

query AdminCouponsQuery($filters: CouponFiltersInput, $sort: [SortInput!], $page: Int, $per_page: Int) {
  convention {
    id
    coupons_paginated(filters: $filters, sort: $sort, page: $page, per_page: $per_page) {
      current_page
      total_pages

      entries {
        ...AdminCouponFields
      }
    }
  }
}
