/* eslint-disable */
import * as Types from '../../graphqlTypes.generated';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type DeleteSignupRankedChoiceMutationVariables = Types.Exact<{
  id: Types.Scalars['ID']['input'];
}>;


export type DeleteSignupRankedChoiceMutationData = { __typename: 'Mutation', deleteSignupRankedChoice: { __typename: 'DeleteSignupRankedChoicePayload', clientMutationId?: string | null } };

export type UpdateSignupRankedChoicePriorityMutationVariables = Types.Exact<{
  id: Types.Scalars['ID']['input'];
  priority: Types.Scalars['Int']['input'];
}>;


export type UpdateSignupRankedChoicePriorityMutationData = { __typename: 'Mutation', updateSignupRankedChoicePriority: { __typename: 'UpdateSignupRankedChoicePriorityPayload', clientMutationId?: string | null } };

export type CreateMyRankedChoiceUserConstraintMutationVariables = Types.Exact<{
  rankedChoiceUserConstraint: Types.RankedChoiceUserConstraintInput;
}>;


export type CreateMyRankedChoiceUserConstraintMutationData = { __typename: 'Mutation', createRankedChoiceUserConstraint: { __typename: 'CreateRankedChoiceUserConstraintPayload', ranked_choice_user_constraint: { __typename: 'RankedChoiceUserConstraint', id: string, start?: string | null, finish?: string | null, maximum_signups: number } } };

export type UpdateRankedChoiceUserConstraintMutationVariables = Types.Exact<{
  id: Types.Scalars['ID']['input'];
  rankedChoiceUserConstraint: Types.RankedChoiceUserConstraintInput;
}>;


export type UpdateRankedChoiceUserConstraintMutationData = { __typename: 'Mutation', updateRankedChoiceUserConstraint: { __typename: 'UpdateRankedChoiceUserConstraintPayload', ranked_choice_user_constraint: { __typename: 'RankedChoiceUserConstraint', id: string, start?: string | null, finish?: string | null, maximum_signups: number } } };

export type DeleteRankedChoiceUserConstraintMutationVariables = Types.Exact<{
  id: Types.Scalars['ID']['input'];
}>;


export type DeleteRankedChoiceUserConstraintMutationData = { __typename: 'Mutation', deleteRankedChoiceUserConstraint: { __typename: 'DeleteRankedChoiceUserConstraintPayload', clientMutationId?: string | null } };


export const DeleteSignupRankedChoiceDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"DeleteSignupRankedChoice"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"id"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ID"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"deleteSignupRankedChoice"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"ObjectValue","fields":[{"kind":"ObjectField","name":{"kind":"Name","value":"id"},"value":{"kind":"Variable","name":{"kind":"Name","value":"id"}}}]}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"clientMutationId"}}]}}]}}]} as unknown as DocumentNode<DeleteSignupRankedChoiceMutationData, DeleteSignupRankedChoiceMutationVariables>;
export const UpdateSignupRankedChoicePriorityDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"UpdateSignupRankedChoicePriority"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"id"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ID"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"priority"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"Int"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"updateSignupRankedChoicePriority"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"ObjectValue","fields":[{"kind":"ObjectField","name":{"kind":"Name","value":"id"},"value":{"kind":"Variable","name":{"kind":"Name","value":"id"}}},{"kind":"ObjectField","name":{"kind":"Name","value":"priority"},"value":{"kind":"Variable","name":{"kind":"Name","value":"priority"}}}]}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"clientMutationId"}}]}}]}}]} as unknown as DocumentNode<UpdateSignupRankedChoicePriorityMutationData, UpdateSignupRankedChoicePriorityMutationVariables>;
export const CreateMyRankedChoiceUserConstraintDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"CreateMyRankedChoiceUserConstraint"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"rankedChoiceUserConstraint"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"RankedChoiceUserConstraintInput"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"createRankedChoiceUserConstraint"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"ObjectValue","fields":[{"kind":"ObjectField","name":{"kind":"Name","value":"rankedChoiceUserConstraint"},"value":{"kind":"Variable","name":{"kind":"Name","value":"rankedChoiceUserConstraint"}}}]}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"ranked_choice_user_constraint"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"FragmentSpread","name":{"kind":"Name","value":"RankedChoiceUserConstraintFields"}}]}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"RankedChoiceUserConstraintFields"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"RankedChoiceUserConstraint"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"start"}},{"kind":"Field","name":{"kind":"Name","value":"finish"}},{"kind":"Field","name":{"kind":"Name","value":"maximum_signups"}}]}}]} as unknown as DocumentNode<CreateMyRankedChoiceUserConstraintMutationData, CreateMyRankedChoiceUserConstraintMutationVariables>;
export const UpdateRankedChoiceUserConstraintDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"UpdateRankedChoiceUserConstraint"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"id"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ID"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"rankedChoiceUserConstraint"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"RankedChoiceUserConstraintInput"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"updateRankedChoiceUserConstraint"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"ObjectValue","fields":[{"kind":"ObjectField","name":{"kind":"Name","value":"id"},"value":{"kind":"Variable","name":{"kind":"Name","value":"id"}}},{"kind":"ObjectField","name":{"kind":"Name","value":"rankedChoiceUserConstraint"},"value":{"kind":"Variable","name":{"kind":"Name","value":"rankedChoiceUserConstraint"}}}]}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"ranked_choice_user_constraint"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"FragmentSpread","name":{"kind":"Name","value":"RankedChoiceUserConstraintFields"}}]}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"RankedChoiceUserConstraintFields"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"RankedChoiceUserConstraint"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"start"}},{"kind":"Field","name":{"kind":"Name","value":"finish"}},{"kind":"Field","name":{"kind":"Name","value":"maximum_signups"}}]}}]} as unknown as DocumentNode<UpdateRankedChoiceUserConstraintMutationData, UpdateRankedChoiceUserConstraintMutationVariables>;
export const DeleteRankedChoiceUserConstraintDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"DeleteRankedChoiceUserConstraint"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"id"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ID"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"deleteRankedChoiceUserConstraint"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"ObjectValue","fields":[{"kind":"ObjectField","name":{"kind":"Name","value":"id"},"value":{"kind":"Variable","name":{"kind":"Name","value":"id"}}}]}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"clientMutationId"}}]}}]}}]} as unknown as DocumentNode<DeleteRankedChoiceUserConstraintMutationData, DeleteRankedChoiceUserConstraintMutationVariables>;