#import "./queries.gql"

mutation UpdateRootSite($siteName: String, $defaultLayoutId: Int, $rootPageId: Int) {
  updateRootSite(input: {
    root_site: {
      site_name: $siteName,
      default_layout_id: $defaultLayoutId,
      root_page_id: $rootPageId
    }
  }) {
    root_site {
      id
      ...RootSiteFields
    }
  }
}
