fragment PageFields on Page {
  id
  name
}

fragment CmsLayoutFields on CmsLayout {
  id
  name
}

fragment RootSiteFields on RootSite {
  id

  root_page {
    ...PageFields
  }

  default_layout {
    ...CmsLayoutFields
  }
}

query RootSiteAdminQuery {
  rootSite {
    ...RootSiteFields
  }

  cmsPages {
    ...PageFields
  }

  cmsLayouts {
    ...CmsLayoutFields
  }
}
