fragment PageFields on Page {
  id
  name
}

fragment CmsLayoutFields on CmsLayout {
  id
  name
}

fragment RootSiteFields on RootSite {
  id
  site_name

  root_page {
    id
    ...PageFields
  }

  default_layout {
    id
    ...CmsLayoutFields
  }
}

query RootSiteAdminQuery {
  rootSite {
    id
    ...RootSiteFields
  }

  cmsPages {
    id
    ...PageFields
  }

  cmsLayouts {
    id
    ...CmsLayoutFields
  }
}
