name: Build doc site

on:
  workflow_call: {}

jobs:
  build-doc-site:
    name: Build doc site
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up docusaurus cache
      uses: actions/cache@v2
      with:
        path: doc-site/.yarn/.cache/webpack
        key: ${{ runner.os }}-doc-site-docusaurus-${{ github.ref }}
        restore-keys: |
          ${{ runner.os }}-doc-site-docusaurus-${{ github.ref }}
          ${{ runner.os }}-doc-site-docusaurus-
    - name: Install libvips42
      run: sudo apt-get update && sudo apt-get install libvips42
    - name: install node
      uses: actions/setup-node@v3
      with:
        cache: yarn
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: yarn install
      run: yarn install
    - name: Generate GraphQL schema
      run: bin/rails graphql:schema:dump
    - name: Build doc site
      run: cd doc-site && yarn run docusaurus graphql-to-doc -f && yarn run build
    - name: Store built site
      uses: actions/upload-artifact@v3
      with:
        name: doc-site
        path: ./doc-site/build
