name: Doc site

on:
  push:
    branches:
      - main
  workflow_dispatch: {}
  pull_request: {}

jobs:
  publish-doc-site:
    name: Publish doc site
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up yarn cache
      uses: actions/cache@v2
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: .yarn/cache
        key: ${{ runner.os }}-doc-site-yarn-${{ github.ref }}-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-doc-site-yarn-${{ github.ref }}-
          ${{ runner.os }}-doc-site-yarn-
    - name: Set up docusaurus cache
      uses: actions/cache@v2
      with:
        path: doc-site/.yarn/.cache/webpack
        key: ${{ runner.os }}-doc-site-docusaurus-${{ github.ref }}
        restore-keys: |
          ${{ runner.os }}-doc-site-docusaurus-${{ github.ref }}
          ${{ runner.os }}-doc-site-docusaurus-
    - name: install node v14
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: yarn install
      run: yarn install
    - name: Generate GraphQL schema
      run: bin/rails graphql:schema:dump
    - name: Build doc site
      run: cd doc-site && yarn run docusaurus graphql-to-doc -f && yarn run build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doc-site/build
        cname: intercode.interactiveliterature.org
